export const WEATHER = "WEATHER";
export const WEATHER_LOADING = "WEATHER_LOADING";
export const WEATHER_ERROR = "WEATHER_ERROR";

export const DASHBOARD = "DASHBOARD";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";

export const CPU_REPORT = "CPU_REPORT";
export const CPU_REPORT_LOADING = "CPU_REPORT_LOADING";
export const CPU_REPORT_ERROR = "CPU_REPORT_ERROR";

export const COMMITS_REPORT = "COMMITS_REPORT";
export const COMMITS_REPORT_LOADING = "COMMITS_REPORT_LOADING";
export const COMMITS_REPORT_ERROR = "COMMITS_REPORT_ERROR";

export const DELIVERIES_REPORT = "DELIVERIES_REPORT";
export const DELIVERIES_REPORT_LOADING = "DELIVERIES_REPORT_LOADING";
export const DELIVERIES_REPORT_ERROR = "DELIVERIES_REPORT_ERROR";
